# --- 1. Secrets ---
# Commands to generate secrets:
# APP_SECRET: openssl rand -base64 32 | tr -d '\n'
# ACCESS_TOKEN_SECRET: openssl rand -base64 32 | tr -d '\n'
# REFRESH_TOKEN_SECRET: openssl rand -base64 32 | tr -d '\n'
# CHROME_TOKEN: openssl rand -hex 32 | tr -d '\n'
# MINIO_ROOT_USER: minioadmin
# MINIO_ROOT_PASSWORD: minioadmin
# POSTGRES_DB: postgres
# POSTGRES_USER: postgres
# POSTGRES_PASSWORD: postgres
# For Google OAuth, generate a client id by going to gcp console API&Services -> Credentials -> Create Credentials

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: reactive-resume
stringData:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "<POSTGRES PASSWORD>" # <<< CHANGE THIS!
  POSTGRES_DB_URL: "postgresql://postgres:<POSTGRES PASSWORD>@postgres:5432/postgres" # <<< CHANGE THIS!
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: reactive-resume
stringData:
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "<MINIO PASSWORD>" # <<< CHANGE THIS!
---
apiVersion: v1
kind: Secret
metadata:
  name: reactive-resume-app-secret
  namespace: reactive-resume
stringData:
  APP_SECRET: "<GENERATE USING OPENSSL>" # <<< GENERATE AND PASTE HERE
  ACCESS_TOKEN_SECRET: "<GENERATE USING OPENSSL>" # <<< GENERATE AND PASTE HERE
  REFRESH_TOKEN_SECRET: "<GENERATE USING OPENSSL>" # <<< GENERATE AND PASTE HERE
  STORAGE_URL: "https://minio.yourdomain.me/reactive-resume-files"
  MAIL_FROM: "noreply@resumebuilder.yourdomain.me"
  CHROME_TOKEN: "<GENERATE USING OPENSSL>" # <<< GENERATE AND PASTE HERE
---
# Optional: Google OAuth secrets (uncomment and fill if you use Google Auth)
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secrets
  namespace: reactive-resume
stringData:
  GOOGLE_CLIENT_ID: "<GENERATE & PASTE HERE>"
  GOOGLE_CLIENT_SECRET: "<GENERATE & PASTE HERE>" # <<< PASTE HERE
---
